version: '3'

services:

  dev:
    image: golang:1.20
    restart: always
    env_file:
      - .env
    ports:
      - ${DEV_PORT}:80
    volumes:
      - ./src:/app
    command: bash -c "cd /app && go run ."
